CREATE SERVICE "recupererVilles" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US01();
CREATE SERVICE "enregistrerVille" TYPE 'RAW' AUTHORIZATION OFF USER "DBA" URL ON AS call US02(:codepostal,:nomville);
CREATE SERVICE "recupererPersonnes" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US03();
CREATE SERVICE "enregistrerPersonne" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US04(:firstName,:lastName,:born,:sex);
CREATE SERVICE "enregistrercas" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US05(:idT,:dateT,:expi,:resul);
CREATE SERVICE "recupererNombreCasPositifsActuellement" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US06();
CREATE SERVICE "recupererTestRecents" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US07();
CREATE SERVICE "recuperercas" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US08();
CREATE SERVICE "ajouterVisite" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON AS call US09(:idP,:code,:datev);


